version: "3"
services:
  database:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=vendas-online"
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    